# this fragment starts the Docker daemon inside the CI-launched
# container
default:

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
#  - deploy

buildtest-job:       # This job runs in the build stage, which runs first.
  stage: build
  variables:
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_TLS_VERIFY: "true"
  services:
    - name: 'docker:dind'
  tags:
   - autoscale
  script:
    - echo "Building docker image..."
    - docker build -t wsisci/benchmarking .
    - echo "Build complete, testing."
#    - docker run --privileged -v /data/:/data wsisci/benchmarking full_test_ci full_test_ci 'CI full test' # Need priv docker for this
    - docker run -v /data/:/data wsisci/benchmarking -v disk disk 'CI test'
    - echo "Testing complete."

include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
