#default:
#  image:
#  name: gitlab-registry.internal.sanger.ac.uk/isg/gitlab-ci-docker-docker

# this fragment starts the Docker daemon inside the CI-launched
# container
.job_template: &start_docker
    before_script:
        - mkdir -p /etc/docker
        - echo '{"registry-mirrors":["https://docker-hub-mirror.internal.sanger.ac.uk:5000"],"default-address-pools":[{"base":"192.168.4.0/16","size":24}]}' > /etc/docker/daemon.json
        - dockerd > /var/log/dockerd.log 2>&1 &
        - sleep 10


stages:          # List of stages for jobs, and their order of execution
  - build
  - test
#  - deploy

buildtest-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
   - autoscale
   - openstack-autoscale-theta-docker-in-docker
  <<: *start_docker
  script:
    - echo "Building docker image..."
    - docker build -t wsisci/benchmarking .
    - echo "Build complete, testing."
#    - docker run --privileged -v /data/:/data wsisci/benchmarking threaded # Need priv docker for this
#    - docker run --privileged -v /data/:/data wsisci/benchmarking timed_command # Need priv docker for this
    - docker run -v /data/:/data wsisci/benchmarking disk
    - echo "Testing complete."

include:
- template: Security/Secret-Detection.gitlab-ci.yml
