#default:
#  image:
#  name: gitlab-registry.internal.sanger.ac.uk/isg/gitlab-ci-docker-docker

# this fragment starts the Docker daemon inside the CI-launched
# container
.job_template: &start_docker
    before_script:
        - mkdir -p /etc/docker
        - dockerd > /var/log/dockerd.log 2>&1 &
        - sleep 10


stages:          # List of stages for jobs, and their order of execution
  - build
  - test
#  - deploy

buildtest-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
   - autoscale
   - openstack-autoscale-theta-docker-in-docker
  <<: *start_docker
  script:
    - echo "Building docker image..."
    - docker build -t wsisci/benchmarking .
    - echo "Build complete, testing."
#    - docker run --privileged -v /data/:/data wsisci/benchmarking full_test_ci full_test_ci 'CI full test' # Need priv docker for this
    - docker run -v /data/:/data wsisci/benchmarking -v disk disk 'CI test'
    - echo "Testing complete."

include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
